addpath /content/mrst-core
addpath /content/mrst-core/params
addpath /content/mrst-core/params/rock
addpath /content/mrst-core/params/wells_and_bc
addpath /content/mrst-core/utils
addpath /content/mrst-core/utils/dataset_manager
addpath /content/mrst-core/utils/dataset_manager/utils
addpath /content/mrst-core/utils/dataset_manager/datasets
addpath /content/mrst-core/utils/dataset_manager/datasets/img
addpath /content/mrst-core/utils/dataset_manager/datasets/downloadFcn
addpath /content/mrst-core/utils/dataset_manager/gui
addpath /content/mrst-core/utils/ad_utils
addpath /content/mrst-core/utils/explore
addpath /content/mrst-core/utils/explore/private
addpath /content/mrst-core/utils/mex
addpath /content/mrst-core/utils/paper_manager
addpath /content/mrst-core/utils/paper_manager/papers
addpath /content/mrst-core/utils/3rdparty
addpath /content/mrst-core/utils/3rdparty/matlab_bgl
addpath /content/mrst-core/utils/3rdparty/matlab_bgl/private
addpath /content/mrst-core/utils/equil
addpath /content/mrst-core/utils/gridtools
addpath /content/mrst-core/utils/gridtools/examples
addpath /content/mrst-core/utils/gridtools/tests
addpath /content/mrst-core/utils/inout
addpath /content/mrst-core/utils/inout/eclipse
addpath /content/mrst-core/utils/inout/eclipse/deckinput_simple
addpath /content/mrst-core/utils/inout/eclipse/deckinput_simple/private
addpath /content/mrst-core/utils/tensorAssembly
addpath /content/mrst-core/utils/tensorAssembly/utils
addpath /content/mrst-core/utils/units
addpath /content/mrst-core/utils/units/constants
addpath /content/mrst-core/examples
addpath /content/mrst-core/examples/experimental
addpath /content/mrst-core/examples/grids
addpath /content/mrst-core/examples/datasets
addpath /content/mrst-core/plotting
addpath /content/mrst-core/plotting/private
addpath /content/mrst-core/modules
addpath /content/mrst-core/gridprocessing
addpath /content/mrst-core/gridprocessing/testgrids
addpath /content/mrst-core/gridprocessing/deprecated
addpath /content/mrst-core/gridprocessing/private
addpath /content/mrst-core/.git
addpath /content/mrst-core/.git/info
addpath /content/mrst-core/.git/refs
addpath /content/mrst-core/.git/refs/tags
addpath /content/mrst-core/.git/refs/heads
addpath /content/mrst-core/.git/refs/remotes
addpath /content/mrst-core/.git/refs/remotes/origin
addpath /content/mrst-core/.git/logs
addpath /content/mrst-core/.git/logs/refs
addpath /content/mrst-core/.git/logs/refs/heads
addpath /content/mrst-core/.git/logs/refs/remotes
addpath /content/mrst-core/.git/logs/refs/remotes/origin
addpath /content/mrst-core/.git/hooks
addpath /content/mrst-core/.git/branches
addpath /content/mrst-core/.git/objects
addpath /content/mrst-core/.git/objects/info
addpath /content/mrst-core/.git/objects/pack
addpath /content/mrst-core/solvers
addpath /content/mrst-autodiff
addpath /content/mrst-autodiff/solvent
addpath /content/mrst-autodiff/solvent/experimental
addpath /content/mrst-autodiff/solvent/experimental/standalone
addpath /content/mrst-autodiff/solvent/experimental/dev
addpath /content/mrst-autodiff/solvent/experimental/dev/data
addpath /content/mrst-autodiff/solvent/experimental/miscibleGasInjection
addpath /content/mrst-autodiff/solvent/experimental/miscibleGasInjection/examples
addpath /content/mrst-autodiff/solvent/experimental/presentation
addpath /content/mrst-autodiff/solvent/experimental/presentation/figures
addpath /content/mrst-autodiff/solvent/experimental/presentation/figures/norne
addpath /content/mrst-autodiff/solvent/experimental/presentation/figures/misc
addpath /content/mrst-autodiff/solvent/experimental/presentation/figures/displacement1D
addpath /content/mrst-autodiff/solvent/experimental/presentation/figures/spe10
addpath /content/mrst-autodiff/solvent/experimental/report
addpath /content/mrst-autodiff/solvent/utils
addpath /content/mrst-autodiff/solvent/examples
addpath /content/mrst-autodiff/solvent/models
addpath /content/mrst-autodiff/compositional
addpath /content/mrst-autodiff/compositional/utils
addpath /content/mrst-autodiff/compositional/utils/units
addpath /content/mrst-autodiff/compositional/examples
addpath /content/mrst-autodiff/compositional/examples/utils
addpath /content/mrst-autodiff/compositional/examples/book-ii
addpath /content/mrst-autodiff/compositional/properties
addpath /content/mrst-autodiff/compositional/properties/components
addpath /content/mrst-autodiff/compositional/models
addpath /content/mrst-autodiff/compositional/models/overall
addpath /content/mrst-autodiff/compositional/models/overall/sequential
addpath /content/mrst-autodiff/compositional/models/natvars
addpath /content/mrst-autodiff/compositional/models/natvars/sequential
addpath /content/mrst-autodiff/compositional/models/natvars/sequential/utils
addpath /content/mrst-autodiff/compositional/models/eos
addpath /content/mrst-autodiff/compositional/fluids
addpath /content/mrst-autodiff/compositional/fluids/blackoil
addpath /content/mrst-autodiff/sequential
addpath /content/mrst-autodiff/sequential/experimental
addpath /content/mrst-autodiff/sequential/statefunctions
addpath /content/mrst-autodiff/sequential/statefunctions/flux
addpath /content/mrst-autodiff/sequential/statefunctions/facility
addpath /content/mrst-autodiff/sequential/utils
addpath /content/mrst-autodiff/sequential/examples
addpath /content/mrst-autodiff/sequential/examples/experimental
addpath /content/mrst-autodiff/sequential/examples/polymer
addpath /content/mrst-autodiff/sequential/models
addpath /content/mrst-autodiff/sequential/models/equations
addpath /content/mrst-autodiff/ad-core
addpath /content/mrst-autodiff/ad-core/simulators
addpath /content/mrst-autodiff/ad-core/simulators/sim_runner
addpath /content/mrst-autodiff/ad-core/simulators/sim_runner/tests
addpath /content/mrst-autodiff/ad-core/timesteps
addpath /content/mrst-autodiff/ad-core/experimental
addpath /content/mrst-autodiff/ad-core/statefunctions
addpath /content/mrst-autodiff/ad-core/statefunctions/utils
addpath /content/mrst-autodiff/ad-core/statefunctions/flux
addpath /content/mrst-autodiff/ad-core/statefunctions/flux/flow_state
addpath /content/mrst-autodiff/ad-core/statefunctions/flux/upwind
addpath /content/mrst-autodiff/ad-core/statefunctions/facility
addpath /content/mrst-autodiff/ad-core/statefunctions/components
addpath /content/mrst-autodiff/ad-core/statefunctions/flowprops
addpath /content/mrst-autodiff/ad-core/statefunctions/flowprops/virtual
addpath /content/mrst-autodiff/ad-core/utils
addpath /content/mrst-autodiff/ad-core/examples
addpath /content/mrst-autodiff/ad-core/examples/book-ii
addpath /content/mrst-autodiff/ad-core/examples/book-ii/utils
addpath /content/mrst-autodiff/ad-core/plotting
addpath /content/mrst-autodiff/ad-core/upscale
addpath /content/mrst-autodiff/ad-core/backends
addpath /content/mrst-autodiff/ad-core/backends/diagonal
addpath /content/mrst-autodiff/ad-core/backends/diagonal/utils
addpath /content/mrst-autodiff/ad-core/backends/diagonal/private
addpath /content/mrst-autodiff/ad-core/backends/diagonal/operators
addpath /content/mrst-autodiff/ad-core/backends/diagonal/operators/mex
addpath /content/mrst-autodiff/ad-core/backends/sparse
addpath /content/mrst-autodiff/ad-core/models
addpath /content/mrst-autodiff/ad-core/models/wells
addpath /content/mrst-autodiff/ad-core/models/aquifers
addpath /content/mrst-autodiff/ad-core/models/facilities
addpath /content/mrst-autodiff/ad-core/models/facilities/vfp
addpath /content/mrst-autodiff/ad-core/models/facilities/separators
addpath /content/mrst-autodiff/ad-core/initialization
addpath /content/mrst-autodiff/ad-core/solvers
addpath /content/mrst-autodiff/ad-core/solvers/experimental
addpath /content/mrst-autodiff/ad-props
addpath /content/mrst-autodiff/ad-props/experimental
addpath /content/mrst-autodiff/ad-props/experimental/co2
addpath /content/mrst-autodiff/ad-props/experimental/blackoil
addpath /content/mrst-autodiff/ad-props/utils
addpath /content/mrst-autodiff/ad-props/simple
addpath /content/mrst-autodiff/ad-props/props
addpath /content/mrst-autodiff/ad-eor
addpath /content/mrst-autodiff/ad-eor/utils
addpath /content/mrst-autodiff/ad-eor/utils/experimental
addpath /content/mrst-autodiff/ad-eor/utils/private
addpath /content/mrst-autodiff/ad-eor/examples
addpath /content/mrst-autodiff/ad-eor/examples/surfactant
addpath /content/mrst-autodiff/ad-eor/examples/surfactant/experimental
addpath /content/mrst-autodiff/ad-eor/examples/surfactant/utils
addpath /content/mrst-autodiff/ad-eor/examples/surfactant-polymer
addpath /content/mrst-autodiff/ad-eor/examples/polymer
addpath /content/mrst-autodiff/ad-eor/examples/polymer/utils
addpath /content/mrst-autodiff/ad-eor/examples/book-ii
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/trailingWaves
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/validation
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/frac-flow
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/slug1D
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/slug1D/utils
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/macrodisp
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/macrodisp/vertSPE10
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/macrodisp/2layer
addpath /content/mrst-autodiff/ad-eor/examples/book-ii/conformanceSPE10
addpath /content/mrst-autodiff/ad-eor/properties
addpath /content/mrst-autodiff/ad-eor/models
addpath /content/mrst-autodiff/ad-eor/models/experimental
addpath /content/mrst-autodiff/ad-eor/models/components
addpath /content/mrst-autodiff/ad-eor/docs
addpath /content/mrst-autodiff/postprocessing
addpath /content/mrst-autodiff/postprocessing/examples
addpath /content/mrst-autodiff/postprocessing/models
addpath /content/mrst-autodiff/postprocessing/models/utils
addpath /content/mrst-autodiff/ad-mechanics
addpath /content/mrst-autodiff/ad-mechanics/utils
addpath /content/mrst-autodiff/ad-mechanics/examples
addpath /content/mrst-autodiff/ad-mechanics/examples/utils
addpath /content/mrst-autodiff/ad-mechanics/models
addpath /content/mrst-autodiff/ad-mechanics/models/fullyCoupled
addpath /content/mrst-autodiff/ad-mechanics/models/fullyCoupled/helpermodels
addpath /content/mrst-autodiff/ad-mechanics/models/fullyCoupled/helpermodels/fluidhelpermodels
addpath /content/mrst-autodiff/ad-mechanics/models/splitting
addpath /content/mrst-autodiff/ad-mechanics/models/splitting/helpermodels
addpath /content/mrst-autodiff/ad-mechanics/models/splitting/fixedStressModels
addpath /content/mrst-autodiff/ad-mechanics/models/splitting/fixedStressModels/helpermodels
addpath /content/mrst-autodiff/ad-fi
addpath /content/mrst-autodiff/ad-fi/ecl
addpath /content/mrst-autodiff/ad-fi/wells
addpath /content/mrst-autodiff/ad-fi/experimental
addpath /content/mrst-autodiff/ad-fi/experimental/origBO
addpath /content/mrst-autodiff/ad-fi/utils
addpath /content/mrst-autodiff/ad-fi/examples
addpath /content/mrst-autodiff/ad-fi/examples/OW_Polymer
addpath /content/mrst-autodiff/ad-fi/examples/OW_Adjoint
addpath /content/mrst-autodiff/ad-fi/examples/SPE3
addpath /content/mrst-autodiff/ad-fi/examples/experimental
addpath /content/mrst-autodiff/ad-fi/examples/experimental/SPE1_adjoint
addpath /content/mrst-autodiff/ad-fi/examples/experimental/thermal
addpath /content/mrst-autodiff/ad-fi/examples/experimental/SPE10_subset
addpath /content/mrst-autodiff/ad-fi/examples/experimental/mouse
addpath /content/mrst-autodiff/ad-fi/examples/experimental/pod
addpath /content/mrst-autodiff/ad-fi/examples/experimental/mpfa
addpath /content/mrst-autodiff/ad-fi/examples/experimental/SPE9
addpath /content/mrst-autodiff/ad-fi/examples/1ph
addpath /content/mrst-autodiff/ad-fi/examples/SPE1
addpath /content/mrst-autodiff/ad-fi/examples/Egg_Model
addpath /content/mrst-autodiff/ad-fi/examples/SPE9
addpath /content/mrst-autodiff/ad-fi/orthodecomp
addpath /content/mrst-autodiff/hybrid-ve
addpath /content/mrst-autodiff/hybrid-ve/utils
addpath /content/mrst-autodiff/hybrid-ve/examples
addpath /content/mrst-autodiff/hybrid-ve/examples/experimental
addpath /content/mrst-autodiff/hybrid-ve/examples/utils
addpath /content/mrst-autodiff/hybrid-ve/models
addpath /content/mrst-autodiff/ad-unittest
addpath /content/mrst-autodiff/ad-unittest/test_sim
addpath /content/mrst-autodiff/ad-unittest/jenkins
addpath /content/mrst-autodiff/ad-unittest/utils
addpath /content/mrst-autodiff/ad-unittest/test_models
addpath /content/mrst-autodiff/ad-unittest/test_utils
addpath /content/mrst-autodiff/ad-unittest/superclasses
addpath /content/mrst-autodiff/ad-unittest/setup
addpath /content/mrst-autodiff/optimization
addpath /content/mrst-autodiff/optimization/utils
addpath /content/mrst-autodiff/optimization/examples
addpath /content/mrst-autodiff/optimization/examples/historyMatch
addpath /content/mrst-autodiff/optimization/examples/model2D
addpath /content/mrst-autodiff/optimization/examples/model2D/utils
addpath /content/mrst-autodiff/optimization/examples/analytic
addpath /content/mrst-autodiff/optimization/examples/analytic/utils
addpath /content/mrst-autodiff/optimization/examples/ensembles
addpath /content/mrst-autodiff/optimization/examples/ensembles/utils
addpath /content/mrst-autodiff/optimization/optim
addpath /content/mrst-autodiff/optimization/objectives
addpath /content/mrst-autodiff/optimization/objectives/experimental
addpath /content/mrst-autodiff/.git
addpath /content/mrst-autodiff/.git/info
addpath /content/mrst-autodiff/.git/refs
addpath /content/mrst-autodiff/.git/refs/tags
addpath /content/mrst-autodiff/.git/refs/heads
addpath /content/mrst-autodiff/.git/refs/remotes
addpath /content/mrst-autodiff/.git/refs/remotes/origin
addpath /content/mrst-autodiff/.git/logs
addpath /content/mrst-autodiff/.git/logs/refs
addpath /content/mrst-autodiff/.git/logs/refs/heads
addpath /content/mrst-autodiff/.git/logs/refs/remotes
addpath /content/mrst-autodiff/.git/logs/refs/remotes/origin
addpath /content/mrst-autodiff/.git/hooks
addpath /content/mrst-autodiff/.git/branches
addpath /content/mrst-autodiff/.git/objects
addpath /content/mrst-autodiff/.git/objects/info
addpath /content/mrst-autodiff/.git/objects/pack
addpath /content/mrst-autodiff/ad-blackoil
addpath /content/mrst-autodiff/ad-blackoil/utils
addpath /content/mrst-autodiff/ad-blackoil/examples
addpath /content/mrst-autodiff/ad-blackoil/examples/experimental
addpath /content/mrst-autodiff/ad-blackoil/examples/utils
addpath /content/mrst-autodiff/ad-blackoil/examples/spe3
addpath /content/mrst-autodiff/ad-blackoil/examples/spe9
addpath /content/mrst-autodiff/ad-blackoil/examples/spe9/utils
addpath /content/mrst-autodiff/ad-blackoil/examples/spe9/compare
addpath /content/mrst-autodiff/ad-blackoil/examples/spe1
addpath /content/mrst-autodiff/ad-blackoil/examples/spe1/utils
addpath /content/mrst-autodiff/ad-blackoil/examples/egg
addpath /content/mrst-autodiff/ad-blackoil/examples/egg/utils
addpath /content/mrst-autodiff/ad-blackoil/examples/spe10
addpath /content/mrst-autodiff/ad-blackoil/models
addpath /content/mrst-autodiff/ad-blackoil/components
addpath /content/mrst-autodiff/example-suite
addpath /content/mrst-autodiff/example-suite/utils
addpath /content/mrst-autodiff/example-suite/examples
addpath /content/mrst-autodiff/example-suite/examples-mrst
addpath /content/mrst-autodiff/example-suite/examples-mrst/utils
addpath /content/MRST-simulations/modules
addpath /content/MRST-simulations/modules/incomp
addpath /content/MRST-simulations/modules/incomp/transport
addpath /content/MRST-simulations/modules/incomp/transport/private
addpath /content/MRST-simulations/modules/incomp/examples
addpath /content/MRST-simulations/modules/incomp/examples/2ph
addpath /content/MRST-simulations/modules/incomp/examples/1ph
addpath /content/MRST-simulations/modules/incomp/fluid
addpath /content/MRST-simulations/modules/incomp/fluid/utils
addpath /content/MRST-simulations/modules/incomp/fluid/incompressible
addpath /content/MRST-simulations/modules/nuwara
addpath /content/MRST-simulations/modules/nuwara/incomp
addpath /content/MRST-simulations/modules/nuwara/incomp/transport
addpath /content/MRST-simulations/modules/nuwara/incomp/transport/private
addpath /content/MRST-simulations/modules/nuwara/incomp/examples
addpath /content/MRST-simulations/modules/nuwara/incomp/examples/2ph
addpath /content/MRST-simulations/modules/nuwara/incomp/examples/1ph
addpath /content/MRST-simulations/modules/nuwara/incomp/fluid
addpath /content/MRST-simulations/modules/nuwara/incomp/fluid/utils
addpath /content/MRST-simulations/modules/nuwara/incomp/fluid/incompressible
